### ISSUE TITLE
怎么使用？怎么配置？

### ISSUE THREAD

**Issue by hanjiangxve** [yzy613/watchdog-ddns#11]
是更新了吗？没找见.json文件啊

**Comment by yzy613** [comment]
#### 你需要先执行 `./watchdog-ddns -init` ，会在当前目录生成 conf 文件夹，里面就有 json 文件

**Comment by yzy613** [comment]
#### 应该没问题了吧？
> 若一天后没有回复，视为问题已解决，将会关闭此问题。若还有问题，请继续评论

**Comment by hanjiangxve** [comment]
watchdog-ddns是个文件吗？我在watchdog-ddns-master下执行./watchdog-ddns -init提示-bash: ./watchdog-ddns: 没有那个文件或目录

**Comment by hanjiangxve** [comment]
./watchdog-ddns-client -init也是提示没有文件

**Comment by yzy613** [comment]
#### 那个命令没写全，你其实可以参考 [README.md](https://github.com/yzy613/watchdog-ddns#%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8) 里面的步骤

**Comment by yzy613** [comment]
> ./watchdog-ddns-client -init也是提示没有文件

#### 不会吧？看看截图

**Comment by hanjiangxve** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzy613/watchdog-ddns"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月16日(星期天) 上午10:17
收件人:&nbsp;"yzy613/watchdog-ddns"<watchdog-ddns@noreply.github.com&gt;;
抄送:&nbsp;"1647866264"<1647866264@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yzy613/watchdog-ddns] 更新了吗 (#11)





  
./watchdog-ddns-client -init也是提示没有文件
  
不会吧？看看截图

**Comment by hanjiangxve** [comment]
![2020-08-16 (1)](https://user-images.githubusercontent.com/49989041/90325101-12bc8300-dfaa-11ea-9f21-98deec6ac60d.png)

**Comment by yzy613** [comment]
#### 你是直接 clone 下来的？？？使用需要去 [releases](https://github.com/yzy613/watchdog-ddns/releases) 下载使用，这里全是源码。。。

**Comment by yzy613** [comment]
#### 描述已更新 [README.md](https://github.com/yzy613/watchdog-ddns#%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8)

**Comment by hanjiangxve** [comment]
在 ./conf/client.json 启用 aliyun请问,这一步如何操作，
![2020-08-16 (2)](https://user-images.githubusercontent.com/49989041/90325401-c2472480-dfad-11ea-88db-ab25d760ca2e.png)

**Comment by yzy613** [comment]
#### 如果你是使用 IPv6，我更推荐使用网卡的 IP（因为 IPv6 存在临时地址，如果没有临时 IPv6 就当我没说）。aliyun 你就把 `aliyun` 的 `false` 改成 `true`

**Comment by yzy613** [comment]
#### 描述已更新 [README.md](https://github.com/yzy613/watchdog-ddns#%E6%94%AF%E6%8C%81%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%95%86)
> 若一天后没有回复，视为问题已解决，将会关闭此问题。若还有问题，请继续评论
